services:
  - type: web
    name: text-translator-service
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: OPENAI_API_KEY
        value: ""
